name: Build and Push to Nuget
jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
 
    - name: setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: publish
      run: |
        cd Squidex.Text
        dotnet pack -c Release

    - name: pack
      run: |
        cd Squidex.Text/bin/Release
        dotnet nuget push *.nupkg --source 'https://api.nuget.org/v3/index.json' -k ${{ secrets.nuget }} 
